// Code generated by mockery. DO NOT EDIT.
// Re-generate with: mockery --config .mockery.yaml
package mocks

import (
	"banka-backend/services/user-service/internal/utils"

	"github.com/stretchr/testify/mock"
)

// MockEmailPublisher is a testify/mock implementation of utils.EmailPublisher.
type MockEmailPublisher struct {
	mock.Mock
}

func (m *MockEmailPublisher) Publish(event utils.EmailEvent) error {
	args := m.Called(event)
	return args.Error(0)
}

// Ensure MockEmailPublisher implements utils.EmailPublisher at compile time.
var _ utils.EmailPublisher = (*MockEmailPublisher)(nil)
