// Code generated by mockery. DO NOT EDIT.
// Re-generate with: mockery --config .mockery.yaml
package mocks

import (
	"banka-backend/services/user-service/internal/domain"

	"github.com/stretchr/testify/mock"
)

// MockUserService is a testify/mock implementation of domain.UserService.
type MockUserService struct {
	mock.Mock
}

func (m *MockUserService) Register(name, email, password string) (*domain.User, error) {
	args := m.Called(name, email, password)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*domain.User), args.Error(1)
}

func (m *MockUserService) Login(email, password string) (accessToken, refreshToken string, err error) {
	args := m.Called(email, password)
	return args.String(0), args.String(1), args.Error(2)
}

func (m *MockUserService) GetByID(id string) (*domain.User, error) {
	args := m.Called(id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*domain.User), args.Error(1)
}

// Ensure MockUserService implements domain.UserService at compile time.
var _ domain.UserService = (*MockUserService)(nil)
