// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type ClientDetail struct {
	UserID         int64    `json:"user_id"`
	LinkedAccounts []string `json:"linked_accounts"`
}

type EmployeeDetail struct {
	UserID     int64          `json:"user_id"`
	Username   string         `json:"username"`
	Position   sql.NullString `json:"position"`
	Department sql.NullString `json:"department"`
}

type Permission struct {
	ID             int32  `json:"id"`
	PermissionCode string `json:"permission_code"`
}

type User struct {
	ID           int64          `json:"id"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	SaltPassword string         `json:"salt_password"`
	UserType     string         `json:"user_type"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	BirthDate    int64          `json:"birth_date"`
	Gender       sql.NullString `json:"gender"`
	PhoneNumber  sql.NullString `json:"phone_number"`
	Address      sql.NullString `json:"address"`
	IsActive     bool           `json:"is_active"`
	CreatedAt    time.Time      `json:"created_at"`
}

type UserPermission struct {
	UserID       int64 `json:"user_id"`
	PermissionID int32 `json:"permission_id"`
}

type VerificationToken struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	Token     string       `json:"token"`
	TokenType string       `json:"token_type"`
	ExpiresAt time.Time    `json:"expires_at"`
	UsedAt    sql.NullTime `json:"used_at"`
}
