// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "banka-backend/services/bank-service/internal/domain"
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockKreditService is an autogenerated mock type for the KreditService type
type MockKreditService struct {
	mock.Mock
}

// ApplyForCredit provides a mock function with given fields: ctx, input
func (_m *MockKreditService) ApplyForCredit(ctx context.Context, input domain.CreateKreditniZahtevInput) (*domain.KreditniZahtev, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ApplyForCredit")
	}

	var r0 *domain.KreditniZahtev
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateKreditniZahtevInput) (*domain.KreditniZahtev, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateKreditniZahtevInput) *domain.KreditniZahtev); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.KreditniZahtev)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CreateKreditniZahtevInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApproveCredit provides a mock function with given fields: ctx, zahtevID
func (_m *MockKreditService) ApproveCredit(ctx context.Context, zahtevID int64) (*domain.Kredit, error) {
	ret := _m.Called(ctx, zahtevID)

	if len(ret) == 0 {
		panic("no return value specified for ApproveCredit")
	}

	var r0 *domain.Kredit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.Kredit, error)); ok {
		return rf(ctx, zahtevID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.Kredit); ok {
		r0 = rf(ctx, zahtevID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Kredit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, zahtevID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllApprovedCredits provides a mock function with given fields: ctx, filter
func (_m *MockKreditService) GetAllApprovedCredits(ctx context.Context, filter domain.GetAllCreditsFilter) ([]domain.Kredit, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAllApprovedCredits")
	}

	var r0 []domain.Kredit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.GetAllCreditsFilter) ([]domain.Kredit, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.GetAllCreditsFilter) []domain.Kredit); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Kredit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.GetAllCreditsFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllPendingRequests provides a mock function with given fields: ctx, filter
func (_m *MockKreditService) GetAllPendingRequests(ctx context.Context, filter domain.GetPendingRequestsFilter) ([]domain.KreditniZahtev, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAllPendingRequests")
	}

	var r0 []domain.KreditniZahtev
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.GetPendingRequestsFilter) ([]domain.KreditniZahtev, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.GetPendingRequestsFilter) []domain.KreditniZahtev); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.KreditniZahtev)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.GetPendingRequestsFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetClientCredits provides a mock function with given fields: ctx, vlasnikID
func (_m *MockKreditService) GetClientCredits(ctx context.Context, vlasnikID int64) ([]domain.Kredit, error) {
	ret := _m.Called(ctx, vlasnikID)

	if len(ret) == 0 {
		panic("no return value specified for GetClientCredits")
	}

	var r0 []domain.Kredit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]domain.Kredit, error)); ok {
		return rf(ctx, vlasnikID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []domain.Kredit); ok {
		r0 = rf(ctx, vlasnikID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Kredit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, vlasnikID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCreditDetails provides a mock function with given fields: ctx, kreditID, vlasnikID
func (_m *MockKreditService) GetCreditDetails(ctx context.Context, kreditID int64, vlasnikID int64) (*domain.Kredit, []domain.Rata, error) {
	ret := _m.Called(ctx, kreditID, vlasnikID)

	if len(ret) == 0 {
		panic("no return value specified for GetCreditDetails")
	}

	var r0 *domain.Kredit
	var r1 []domain.Rata
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (*domain.Kredit, []domain.Rata, error)); ok {
		return rf(ctx, kreditID, vlasnikID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) *domain.Kredit); ok {
		r0 = rf(ctx, kreditID, vlasnikID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Kredit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) []domain.Rata); ok {
		r1 = rf(ctx, kreditID, vlasnikID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]domain.Rata)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, int64) error); ok {
		r2 = rf(ctx, kreditID, vlasnikID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RejectCredit provides a mock function with given fields: ctx, zahtevID
func (_m *MockKreditService) RejectCredit(ctx context.Context, zahtevID int64) error {
	ret := _m.Called(ctx, zahtevID)

	if len(ret) == 0 {
		panic("no return value specified for RejectCredit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, zahtevID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProcessFirstInstallment provides a mock function with given fields: ctx, kreditID
func (_m *MockKreditService) ProcessFirstInstallment(ctx context.Context, kreditID int64) (bool, time.Time, error) {
	ret := _m.Called(ctx, kreditID)

	if len(ret) == 0 {
		panic("no return value specified for ProcessFirstInstallment")
	}

	var r0 bool
	var r1 time.Time
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (bool, time.Time, error)); ok {
		return rf(ctx, kreditID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) bool); ok {
		r0 = rf(ctx, kreditID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if rf, ok := ret.Get(1).(func(context.Context, int64) time.Time); ok {
		r1 = rf(ctx, kreditID)
	} else {
		r1 = ret.Get(1).(time.Time)
	}
	if rf, ok := ret.Get(2).(func(context.Context, int64) error); ok {
		r2 = rf(ctx, kreditID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// NewMockKreditService creates a new instance of MockKreditService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKreditService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKreditService {
	mock := &MockKreditService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
