// Code generated by mockery. DO NOT EDIT.
// Re-generate with: mockery --config .mockery.yaml
package mocks

import (
	notifsmtp "banka-backend/services/notification-service/internal/smtp"

	"github.com/stretchr/testify/mock"
)

// MockSMTPSender is a testify/mock implementation of smtp.Sender.
type MockSMTPSender struct {
	mock.Mock
}

func (m *MockSMTPSender) Send(recipient, subject, bodyHTML string) error {
	args := m.Called(recipient, subject, bodyHTML)
	return args.Error(0)
}

// Ensure MockSMTPSender implements smtp.Sender at compile time.
var _ notifsmtp.Sender = (*MockSMTPSender)(nil)
