// Code generated by mockery. DO NOT EDIT.
// Re-generate with: mockery --config .mockery.yaml
package mocks

import (
	"banka-backend/services/notification-service/internal/domain"

	"github.com/stretchr/testify/mock"
)

// MockNotificationService is a testify/mock implementation of domain.NotificationService.
type MockNotificationService struct {
	mock.Mock
}

func (m *MockNotificationService) SendEmail(n *domain.Notification) error {
	args := m.Called(n)
	return args.Error(0)
}

// Ensure MockNotificationService implements domain.NotificationService at compile time.
var _ domain.NotificationService = (*MockNotificationService)(nil)
